services:
  - docker

# show correct language tag in Travis CI build
language: cpp

env:
   matrix:
    - USER: robot    ## user name : robot


before_install:
  - docker run -d -u $USER -it --name ci_xenial -v $(pwd):/home/robot/wiki_barebone:rw aragdoll/docker_ubuntu:xenial_with_user_robot;
  # grant user permissions to the robot home folder
  - docker exec -u $USER -it ci_xenial /bin/bash -c "sudo chown robot:robot -R /home/robot";


install:
  - docker exec -u $USER -it ci_xenial /bin/bash -c "/home/robot/wiki_barebone/install.sh";

script:
  - docker exec -u $USER -t ci_xenial /bin/bash -c "/home/robot/wiki_barebone/setup.sh"

notifications:
    email: false
