services:
  - docker

# show correct language tag in Travis CI build
language: cpp

env:
   matrix:
    - USER: robot    ## use ros and ubuntu docker image from docker hub


before_install:
  - docker run -d -u $USER -it --name ci_xenial -v $(pwd):/home/robot/wiki_barebone:rw aragdoll/docker_ubuntu:xenial_with_user_robot;
  # grant user permissions to the robot home folder
  - docker exec -u $USER -it ci_xenial /bin/bash -c "sudo chown robot:robot -R /home/robot";


install:
  - docker exec -u $USER -it ci_xenial /bin/bash -c "/home/robot/wiki_barebone/install.bash";

## docker exec command allows to execute a command or a series of Linux shell commands inside our container.
## -t options allocates a pseudo-TTY for this command(-s) so you can view output or error messages, if any, in Travis CI build log.
## xenial is the name of a container we send commands to.
## bash -c means that we will execute the following string in bash shell.
## YAML allows to span strings enclosed in quotes (") into several lines and I recommend to put each command on a separate line for
## better readability. Bash commands are separated with a semicolon (;).

script:
  - docker exec -u $USER -t ci_xenial /bin/bash -c "/home/robot/wiki_barebone/setup.bash"

notifications:
    email: false
